# Generated by Django 5.1 on 2025-05-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbtemplates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='template',
            name='last_changed',
            field=models.DateTimeField(auto_now=True, verbose_name='last changed'),
        ),
    ]
