# Generated by Django 5.2 on 2025-05-29 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbtemplates', '0002_alter_template_creation_date_and_more'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='TemplateSite',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
                        ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbtemplates.template')),
                    ],
                    options={
                        'db_table': 'django_template_sites',
                    },
                ),
                migrations.AlterField(
                    model_name='template',
                    name='sites',
                    field=models.ManyToManyField(blank=True, through='dbtemplates.TemplateSite', to='sites.site', verbose_name='sites'),
                ),
                migrations.AddConstraint(
                    model_name='templatesite',
                    constraint=models.UniqueConstraint(fields=('template', 'site'), name='django_template_sites_template_id_site_id_d00c11a4_uniq'),
                ),
                migrations.AddConstraint(
                    model_name='templatesite',
                    constraint=models.UniqueConstraint(fields=('template__name', 'site'), name='template_name_site_uniq'),
                ),
            ],
        ),
    ]
