# Generated by Django 5.1 on 2025-05-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbtemplates', '0002_alter_template_creation_date_and_more'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['name'], name='template_name_idx'),
        ),
    ]
