# Generated by Django 5.2 on 2025-05-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbtemplates', '0002_alter_template_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(help_text="Example: 'flatpages/default.html'", max_length=100, unique=True, verbose_name='name'),
        ),
    ]
